services:
  postgres:
    image: postgres:17-alpine
    container_name: boletim-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boletim
    volumes:
      - boletim_pg_data:/var/lib/postgresql/data

volumes:
  boletim_pg_data:
